services:
  noetic:
    image: noetic:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F anything
    environment:
      # Display X Server GUI.
      - DISPLAY
      # Fix a bug with QT
      - QT_X11_NO_MITSHM=1
      # - LIBGL_ALWAYS_SOFTWARE=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "/dev:/dev"
      - ./catkin_ws/src:/root/catkin_ws/src
      - ./catkin_ws/results:/root/catkin_ws/results

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    privileged: true
    tty: true
    stdin_open: true
    network_mode: host